In [9]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

def ler_arquivo(nome_arquivo):
    arq = open(nome_arquivo, 'r')
    lista = []
    for linha in arq:
        valores = linha.strip().split(';')
        lista.append(valores)
    arq.close()
    lista.pop(0)    
    #nomes = [valor[0] for valor in lista]
    nomes, notas = zip(*[(l[0], map(lambda item: float(item), l[1:])) for l in lista])
    
    return np.array(nomes), np.array(notas)
    
nomes, notas = ler_arquivo('notas.csv')
cores = ['red','green','blue']
marcadores = ['o','^','s']

print(notas)
notas = np.array(notas)
print(notas)

# for index, nome in enumerate(nomes):
#     plt.plot(notas[index], c=cores[index], marker=marcadores[index], ms=8, label=nome)

# plt.legend(loc='lower left')
# plt.show()
#print(nomes
#print(notas

[<map object at 0x000001A826C1C640> <map object at 0x000001A826C5A950>
[<map object at 0x000001A826C1C640> <map object at 0x000001A826C5A950>


In [10]:
import numpy as np

vetor = np.array([10,20,50,70,30])
print('Dimensões (eixos):', vetor.ndim)
vetor

Dimensões (eixos): 1


array([10, 20, 50, 70, 30])

In [11]:
vetor = np.insert(vetor,1,90)
vetor

array([10, 90, 20, 50, 70, 30])

In [12]:
import numpy as np
matriz = np.array([[1,2,3],[4,5,6],[7,8,9]])
print('Dimensões (eixos):', matriz.ndim)
print(matriz)
print('Soma de colunas', matriz.sum(axis=0))
print('Soma de linhas', matriz.sum(axis=1))

Dimensões (eixos): 2
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Soma de colunas [12 15 18]
Soma de linhas [ 6 15 24]


In [13]:
import numpy as np

vetor = np.array([1,2,3])
print('Dimensões (eixos):', vetor.ndim, vetor.__repr__())

Dimensões (eixos): 1 array([1, 2, 3])


In [14]:
vetor = np.append(vetor, 4)
print('Dimensões (eixos):', vetor.ndim, vetor.__repr__())

Dimensões (eixos): 1 array([1, 2, 3, 4])


In [15]:
vetor = np.append(vetor, [5,6,7])
print('Dimensões (eixos):', vetor.ndim, vetor.__repr__())

Dimensões (eixos): 1 array([1, 2, 3, 4, 5, 6, 7])


In [16]:
print('Inclusão de uma linha')
np.append(matriz, [[0,0,0]], axis=0)

Inclusão de uma linha


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [0, 0, 0]])

In [17]:
print('Inclusão de uma coluna')
print(matriz)
coluna = np.array([[0,0,0]])
print('Novos dados:', coluna, coluna.shape)

Inclusão de uma coluna
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Novos dados: [[0 0 0]] (1, 3)


In [18]:
coluna = np.reshape(coluna, (3,1))
print(coluna, coluna.shape)

[[0]
 [0]
 [0]] (3, 1)


In [19]:
np.append(matriz, coluna, axis=1)

array([[1, 2, 3, 0],
       [4, 5, 6, 0],
       [7, 8, 9, 0]])

In [20]:
sum(range(1, 111111119))

6172840327160521

In [21]:
np.arange(1, 111111119).sum()

1660199625

In [22]:
soma = 0
for i in range(1, 111111119):
    soma += i
print(soma)

6172840327160521


In [23]:
import numpy as np
vetor = np.array([10,20,30,40,50])
print('Dimensões (eixos):', vetor.ndim, vetor.__repr__())

Dimensões (eixos): 1 array([10, 20, 30, 40, 50])


In [24]:
np.delete(vetor, 2)

array([10, 20, 40, 50])

In [25]:
import numpy as np
matriz = np.array([[1,2,3],[4,5,6],[7,8,9]])
print('Dimensões (eixos):', matriz.ndim)
print(matriz)

Dimensões (eixos): 2
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [26]:
np.delete(matriz,1,0)

array([[1, 2, 3],
       [7, 8, 9]])

In [27]:
np.delete(matriz,1,1)

array([[1, 3],
       [4, 6],
       [7, 9]])

In [28]:
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
import pandas as pd
serie = pd.Series