In [2]:
# -*- coding: UTF-8 -*-
import numpy as np
lista = [10, 20, 30, 40, 50, 60]
np_array = np.array(lista)
print type(np_array), np_array

 <type 'numpy.ndarray'> [10 20 30 40 50 60]


In [4]:
sum(np_array)

210

In [5]:
np_array[2:5]

array([30, 40, 50])

In [6]:
mat = np.array([[1,2,3],[4,5,6],[7,8,9]])
print type(mat), '\n', mat

<type 'numpy.ndarray'> 
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
print 'mat[1]:', mat[1], ' - mat[1][1]:', mat[1][1]

mat[1]: [4 5 6]  - mat[1][1]: 5


In [10]:
print 'mat[:,0]:', mat[:,0]

mat[:,0]: [1 4 7]


In [11]:
print mat

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
print 'Transposta:\n', mat.transpose()

Transposta:
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [13]:
m1 = np.array([[1,2],[3,4]])
print m1
m2 = np.array([[5,6],[7,8]])
print m2
m1 + m2

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


array([[ 6,  8],
       [10, 12]])

In [14]:
m1 - m2

array([[-4, -4],
       [-4, -4]])

In [15]:
m3 = np.array([3,5,8,4])
m3.sum()

20

In [16]:
m3.argmax()

2

In [17]:
m3.argmin()

0

In [23]:
matrix = mat.copy()
print matrix
print 'matrix.mean():', matrix.mean() # Media dos elementos
print 'matrix.diagonal():', matrix.diagonal() # diagonal
print 'matrix.ndim:', matrix.ndim # dimensao

[[1 2 3]
 [4 5 6]
 [7 8 9]]
matrix.mean(): 5.0
matrix.diagonal(): [1 5 9]
matrix.ndim: 2


In [24]:
lista = [80, 20, 40, 50, 90]
a = np.array(lista)
a[1:5]

array([20, 40, 50, 90])

In [25]:
a[::2]

array([80, 40, 90])

In [26]:
a[-3:]

array([40, 50, 90])

In [27]:
b = a[:]
print 'array a\n',a
print 'array b\n',b
print '**** Alterando b[0] = 100'
b[0] = 100
print 'array a\n',a
print 'array b\n',b


array a
[80 20 40 50 90]
array b
[80 20 40 50 90]
**** Alterando b[0] = 100
array a
[100  20  40  50  90]
array b
[100  20  40  50  90]
